### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by damnever** [hxdtp/hxdtp#3]
- [x] Add `type CallFunc(Request)(Response, error)` and middlewares for client side.
- [x] Middleware chain for server side
- [ ] Sink timeout to transport layer?
- [ ] Remove `interface{}` in headers, use a concrete type for usability 
- [ ] Hooks to handle server side errors(metrics..)
- [x] Send/handle requests concurrently on one connection
- [ ] Documents, magic numbers and configurable options..
- [ ] More test cases, benchmarks
- [ ] Optimization: reuse buffer/object, etc.
    - [x] Avoid allocation inside Protocol, pass a reusable object instead
    - [ ] Split transport to two parts: reader and writer
    - [ ] Reuse buffered transport
    - [ ] Better concurrency model: goroutine pool?
